site_name: D2F-vLLM
site_description: Documentation for the D2F-vLLM
site_url: https://d2f_vllm.org.cn
repo_url: https://github.com/zhijie-group/D2F
theme:
  name: material
nav:
  - Home: index.md
  - Usage: usage.md
  - Implementation: impl.md
markdown_extensions:
  - toc:
      permalink: true
  - fenced_code
plugins:
  - search
site_dir: site
use_directory_urls: true
