theme:
  name: material
site_name: d2f_engine
site_url: https://zhijie-group.github.io/d2fengine
site_author: D2F Team (SJTU DENG Lab)
nav:
  - Home: index.md
  - User Guide:
    - Install from Source: user-guide/1_install.md
  - Implementation:
    - Overview: impl/0_overview.md
    - Engine: impl/1_engine.md
    - Scheduer: impl/2_scheduler.md
    - KVCache Manager: impl/3_kvcache_manager.md
    - Model Runner: impl/4_model_runner.md
    - Model Registry: impl/5_model_registry.md
    - Kernels: impl/6_kernels.md
  - License: license.md
  